version: "3"
services:
  mriq-php:
    container_name: "mriq-php"
    build:
      dockerfile: "./docker/Dockerfile.dev"
      context: "./"
    links:
      - "mriq-mariadb:mariadb.host"
      - "mriq-redis:redis.host"
    ports:
      - 8080:8080
    volumes:
      - "./:/mriq"
    restart: always
  mriq-mariadb:
    image: "mariadb:10.6"
    container_name: "mriq-mariadb"
    volumes:
        - "._mysql_data_dir/:/var/lib/mysql"
    ports:
      - 3307:3306
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    restart: always
  mriq-redis:
    image: "redis:alpine"
    container_name: "mriq-redis"
    restart: always
