apiVersion: v1
kind: ConfigMap
metadata:
  name: mriq-configmap
data:
  nginx-config: |
    upstream app_server {
      server 127.0.0.1:9000;
      keepalive 64;
    }

    server {
      server_name _;

      location / {
          root /mriq/public/;

          try_files $uri /index.php$is_args$args;
      }

      location ~ ^/index\.php(/|$) {
          client_max_body_size 50m;

          fastcgi_pass app_server;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
          include fastcgi_params;
          fastcgi_param SCRIPT_FILENAME /mriq/public/index.php;
      }

      error_log /dev/stderr debug;
      access_log /dev/stdout;
     }
